package main;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.List;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/quizze")
public class QuizzeController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private QuizzeRepository quizzeRepository;
    @Autowired
    private QuizzesService quizzesService;

    @GetMapping(path="/all")
    public @ResponseBody
    Iterable<Quizze> getAllQuizzes() {
        // This returns a JSON or XML with the users
        return quizzesService.getAllQuizzes();
    }
    @RequestMapping(value = "user/{id}")
    public List<String> getRecommendedQuizzes(@PathVariable Integer id)throws Exception
    {
        return quizzesService.getRecommendedQuizzes(id);

    }
     @RequestMapping(value = "/{id}")
    public List<String> getQuizzes(@PathVariable Integer id)
    {
        return quizzesService.getQuizzes(id);

    }
}
